### ISSUE TITLE
Missing default datasources on page load.

### ISSUE THREAD

**Issue by joachimvh** [comunica/jQuery-Widget.js#8]
When loading the widget, if the first query selected is one with multiple datasources, only one of those datasources is selected.

When the query gets selected through the dropdown box, all the datasources appear though. But in my use case there is only 1 query so it is actually impossible to select another query... unless you refresh the page weirdly enough. When refreshing the page suddenly "select a query" box is empty (might be another bug), and the query can be selected again (in which case the missing datasources appear).

**Comment by rubensworks** [comment]
This issue was wrongly closed...

**Comment by ColinMaudry** [comment]
Same problem here. Has the root cause been identified?

**Comment by ColinMaudry** [comment]
The problem seems to be related to how `selectedDatasources` are populated when the datasource selection menu is initialized. Am I right?

If so, a workaround may be to hardcode the desired `selectedDatasources` after running `queries-to-json`. I tried, but the format of the `selectedDatasources` block doesn't seem the same as for `datasources`, and that didn't work.

**Comment by rubensworks** [comment]
I'm not sure what the exact problem is, we haven't found the time yet to look into this.

> If so, a workaround may be to hardcode the desired selectedDatasources in queries.json after running queries-to-json

I think we can get to an easier solution that does not require changing the `queries.json` file. (Not sure what yet though)
